version: '3.8'

services:
  nextjs:
    build:
      context: ./client
    ports:
      - "3000:3000"  # For frontend
      - "5000:5000"  # For backend
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
    restart: always
    networks:
      - nutri-scan
    command: ["sh", "-c", "npm run server & npm run dev"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build:
      context: ./server
    container_name: django_server
    command: ["./wait-for-it.sh", "nextjs:5000", "-t", "300", "--", "gunicorn", "server.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - ./server:/app
      - ./wait-for-it.sh:/wait-for-it.sh  # Add the wait-for-it script
    ports:
      - "8000:8000"
    networks: 
      - nutri-scan

networks:
  nutri-scan:
    driver: bridge
