name: Check for Secrets

on: [push, pull_request]

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # You can specify a different Node.js version if needed

      - name: Install secretlint
        run: npm install -g @secretlint/secretlint

      - name: Check for secrets
        run: secretlint --config .secretlintrc.yml
