name: Check for Secrets

on: [push]

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for secrets
        uses: secretlint/secretlint-action@v1
        with:
          config: .secretlintrc.yml
